export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        maven: {
          cream: '#FDF6EC',
          paper: '#FFFBF4',
          sand: '#F3EAD9',
          line: '#E7DAC2',
          pine: '#0A3C2E',
          'pine-dark': '#062A20',
          moss: '#4A7C6F',
          sage: '#DDE8DF',
          clay: '#E85D3F',
          'clay-dark': '#C84A30',
          blush: '#F9DEDC',
          'blush-ink': '#A24C63',
          sky: '#DCEBF3',
          'sky-ink': '#3E6E8E',
          butter: '#F6E7C1',
          'butter-ink': '#8A6A2F',
        },
        nb: {
          ink: '#132A2C',
          teal: '#0A3C2E',
          'teal-dark': '#062A20',
          sage: '#4A7C6F',
          sand: '#F3EAD9',
          paper: '#FFFBF4',
          clay: '#E85D3F',
          'clay-dark': '#C84A30',
          line: '#E7DAC2',
        },
        pastel: {
          tan: '#F6E7C1',
          'tan-ink': '#8A6A2F',
          pink: '#F9DEDC',
          'pink-ink': '#A24C63',
          blue: '#DCEBF3',
          'blue-ink': '#3E6E8E',
          green: '#DDE8DF',
          'green-ink': '#2F6B4F',
        },
      },
      fontFamily: {
        serif: ['Fraunces', '"Source Serif Pro"', 'Georgia', 'serif'],
        sans: ['Inter', '-apple-system', 'Segoe UI', 'Helvetica', 'sans-serif'],
      },
      maxWidth: { content: '1280px' },
    },
  },
};
